import { defineConfig } from "eslint/config";
import js from "@eslint/js";
import ts from "typescript-eslint";
import stylistic from "@stylistic/eslint-plugin";
import globals from "globals";
import reactPlugin from "eslint-plugin-react";
import pluginPromise from "eslint-plugin-promise";
import { globalIgnores } from "@eslint/config-helpers";
import eslintPluginJsonc from "eslint-plugin-jsonc";
// import css from "@eslint/css";


export default defineConfig([
  // css disabled: issue with no-irregular-whitespace
  // {
  //   files: ["**/*.css"],
  //   language: "css/css",
  //   plugins: { css },
  //   extends: ["css/recommended"],
  //   rules: { 'no-irregular-whitespace': 'off' },
  // },

  js.configs.recommended,
  ...ts.configs.recommended,
  ...ts.configs.stylistic,
  ...eslintPluginJsonc.configs["flat/recommended-with-jsonc"],
  stylistic.configs.customize({}),
  {
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
  },
  {
    files: [
      "./*.{js,ts,jsx,tsx}",
      "src/+(server|client|shared)/**/*.{js,ts,jsx,tsx}",
      "tests/**/*.{js,ts,jsx,tsx}",
      "scripts/**/*.{js,ts,jsx,tsx}",
    ],
    settings: {
      react: {
        version: "detect",
      },
    },
    ...reactPlugin.configs.flat.recommended,
    languageOptions: {
      globals: globals.node,
      parser: ts.parser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
          project: true,
        },
      },
    },
    ...pluginPromise.configs["flat/recommended"],
    rules: {
      // See https://github.com/eslint-community/eslint-plugin-promise
      "promise/always-return": "warn",
      "promise/avoid-new": "off",
      "promise/catch-or-return": "warn",
      "promise/no-callback-in-promise": "warn",
      "promise/no-return-wrap": "warn",
      "promise/param-names": "warn",
      "promise/no-native": "off",
      "promise/no-nesting": "warn",
      "promise/no-promise-in-callback": "warn",
      "promise/no-new-statics": "warn",
      "promise/no-return-in-finally": "warn",
      "promise/valid-params": "warn",
      "promise/no-multiple-resolved": "warn",

      // See https://eslint.org/docs/latest/rules
      "eqeqeq": [ "warn", "smart" ],
      "no-var": [ "warn" ],
      "object-shorthand": [ "warn", "always", { avoidExplicitReturnArrows: true } ],
      "@typescript-eslint/one-var": [ "off" ],
      "@typescript-eslint/no-namespace": [ "off" ],
      "prefer-arrow-callback": [ "warn" ],
      "@typescript-eslint/no-unused-vars": [ "warn", {
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      } ],

      // See https://eslint.style/rules
      "@stylistic/array-bracket-newline": [ "warn", "consistent" ],
      "@stylistic/array-bracket-spacing": [ "warn", "always", { arraysInArrays: false } ],
      "@stylistic/arrow-parens": [ "warn", "always" ],
      "@stylistic/arrow-spacing": "warn",
      "@stylistic/block-spacing": "warn",
      "@stylistic/brace-style": [ "warn", "1tbs", { allowSingleLine: true } ],
      "@stylistic/comma-dangle": [ "warn", "always-multiline" ],
      "@stylistic/comma-spacing": [ "warn", { before: false, after: true } ],
      "@stylistic/computed-property-spacing": "off",
      "@stylistic/curly-newline": "off",
      "@stylistic/dot-location": [ "warn", "property" ],
      "@stylistic/eol-last": [ "warn", "always" ],
      "@stylistic/function-call-argument-newline": "off",
      "@stylistic/generator-star-spacing": "off",
      "@stylistic/implicit-arrow-linebreak": "off",
      "@stylistic/indent": [ "warn", 2 ],
      "@stylistic/indent-binary-ops": [ "warn", 2 ],
      "@stylistic/jsx-child-element-spacing": "warn",
      "@stylistic/jsx-closing-bracket-location": [ "warn", "line-aligned" ],
      "@stylistic/jsx-closing-tag-location": [ "warn", "line-aligned" ],
      "@stylistic/jsx-curly-brace-presence": "off",
      "@stylistic/jsx-curly-newline": "warn",
      "@stylistic/jsx-curly-spacing": "off",
      "@stylistic/jsx-equals-spacing": [ "warn", "always" ],
      "@stylistic/jsx-first-prop-new-line": "off",
      "@stylistic/jsx-function-call-newline": "off",
      "@stylistic/jsx-indent-props": [ "warn", 2 ],
      "@stylistic/jsx-newline": [ "warn", { prevent: true } ],
      "@stylistic/jsx-one-expression-per-line": "off",
      "@stylistic/jsx-pascal-case": [ "warn", { allowNamespace: true } ],
      "@stylistic/jsx-quotes": [ "warn", "prefer-double" ],
      "@stylistic/jsx-tag-spacing": [ "warn", { beforeSelfClosing: "always" } ],
      "@stylistic/jsx-wrap-multilines": [ "warn", {
        declaration: "parens-new-line",
        assignment: "parens-new-line",
        return: "parens-new-line",
        arrow: "parens-new-line",
        condition: "parens-new-line",
        logical: "parens-new-line",
        prop: "parens-new-line",
        propertyValue: "parens-new-line",
      } ],
      "@stylistic/key-spacing": [ "warn", { mode: "minimum" } ],
      "@stylistic/keyword-spacing": "warn",
      "@stylistic/line-comment-position": "off",
      "@stylistic/linebreak-style": [ "warn", "unix" ],
      "@stylistic/lines-around-comment": "off",
      "@stylistic/lines-between-class-members": "off",
      "@stylistic/max-len": "off",
      "@stylistic/max-statements-per-line": "off",
      "@stylistic/member-delimiter-style": [ "warn", { multiline: { delimiter: "semi" } } ],
      "@stylistic/multiline-comment-style": "off",
      "@stylistic/multiline-ternary": [ "warn", "always-multiline" ],
      "@stylistic/new-parens": "warn",
      "@stylistic/newline-per-chained-call": [ "warn", { ignoreChainWithDepth: 2 } ],
      "@stylistic/no-confusing-arrow": "off",
      "@stylistic/no-extra-parens": "off",
      "@stylistic/no-extra-semi": "warn",
      "@stylistic/no-floating-decimal": "warn",
      "@stylistic/no-mixed-operators": "warn",
      "@stylistic/no-mixed-spaces-and-tabs": "warn",
      "@stylistic/no-multi-spaces": [ "warn", { ignoreEOLComments: true } ],
      "@stylistic/no-multiple-empty-lines": [ "warn", { max: 2, maxEOF: 0 } ],
      "@stylistic/no-tabs": "warn",
      "@stylistic/no-trailing-spaces": "warn",
      "@stylistic/no-whitespace-before-property": "warn",
      "@stylistic/nonblock-statement-body-position": "off",
      "@stylistic/object-curly-newline": "off",
      "@stylistic/object-curly-spacing": [ "warn", "always" ],
      "@stylistic/object-property-newline": "off",
      "@stylistic/one-var-declaration-per-line": "off",
      "@stylistic/operator-linebreak": [ "warn", "after", { overrides: { "?": "before", ":": "before" } } ],
      "@stylistic/padded-blocks": "off",
      "@stylistic/padding-line-between-statements": "off",
      "@stylistic/quote-props": [ "warn", "consistent-as-needed" ],
      "@stylistic/quotes": [ "warn", "double" ],
      "@stylistic/semi": [ "warn", "always" ],
      "@stylistic/semi-spacing": "warn",
      "@stylistic/space-before-blocks": "warn",
      "@stylistic/space-before-function-paren": [ "warn", "never" ],
      "@stylistic/space-in-parens": [ "warn", "never" ],
      "@stylistic/space-infix-ops": "warn",
      "@stylistic/space-unary-ops": "warn",
      "@stylistic/spaced-comment": [ "warn", "always" ],
      "@stylistic/switch-colon-spacing": "warn",
      "@stylistic/template-curly-spacing": "warn",
      "@stylistic/template-tag-spacing": "off",
      "@stylistic/type-annotation-spacing": "warn",
      "@stylistic/type-generic-spacing": "off",
      "@stylistic/type-named-tuple-spacing": [ "warn" ],
      "@stylistic/wrap-iife": [ "warn", "outside" ],
      "@stylistic/wrap-regex": "off",
      "@stylistic/yield-star-spacing": "warn",
    },
  },
  globalIgnores([
    "**/node_modules",
    "**/dist",
    "**/build",
    "**/src/!(server|client|shared)",
  ]),
]);
